additions

diff --git a/bin/mkproject b/bin/mkproject
--- a/bin/mkproject
+++ b/bin/mkproject
@@ -1,21 +1,23 @@
 #!/bin/sh
 if [ -d ".project" ]; then
-    echo ".project already exists; aborting"
-    exit 1
+  echo ".project already exists; aborting"
+  exit 1
 fi
+
 if [ -n "$1" ]; then
-    base="$HOME/p/$1/.project"
-    if [ -d "$base" ]; then
-        echo "using $base as template"
-        cp -R $base .
-    else
-        echo "$1 is not a project; aborting"
-        exit 1
-    fi
+  base="$HOME/p/$1/.project"
+  if [ -d "$base" ]; then
+    echo "using $base as template"
+    cp -R $base .
+  else
+    echo "$1 is not a project; aborting"
+    exit 1
+  fi
 else
-    mkdir .project
-    echo ".." > .project/tag-targets
-    touch .project/launch.sh
+  mkdir .project
+  echo ".." > .project/tag-targets
+  touch .project/launch.sh
 fi
+
 generate-project-tags .project
 echo ".project created"
